// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: protoc/customer.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomerClient is the client API for Customer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomerClient interface {
	CreateCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*CustomerModel, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error)
	UpdateCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*CustomerModel, error)
	DeleteCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*DeleteCustomerResponse, error)
	GetAllCustomer(ctx context.Context, in *GetAllCustomerRequest, opts ...grpc.CallOption) (*AllCustomerResponse, error)
	AddTagsCustomer(ctx context.Context, in *AddTagsCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error)
	DeleteTagsOfCustomer(ctx context.Context, in *DeleteTagsOfCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error)
}

type customerClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomerClient(cc grpc.ClientConnInterface) CustomerClient {
	return &customerClient{cc}
}

func (c *customerClient) CreateCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*CustomerModel, error) {
	out := new(CustomerModel)
	err := c.cc.Invoke(ctx, "/asm.Customer/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error) {
	out := new(CustomerModel)
	err := c.cc.Invoke(ctx, "/asm.Customer/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) UpdateCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*CustomerModel, error) {
	out := new(CustomerModel)
	err := c.cc.Invoke(ctx, "/asm.Customer/UpdateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteCustomer(ctx context.Context, in *CustomerModel, opts ...grpc.CallOption) (*DeleteCustomerResponse, error) {
	out := new(DeleteCustomerResponse)
	err := c.cc.Invoke(ctx, "/asm.Customer/DeleteCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) GetAllCustomer(ctx context.Context, in *GetAllCustomerRequest, opts ...grpc.CallOption) (*AllCustomerResponse, error) {
	out := new(AllCustomerResponse)
	err := c.cc.Invoke(ctx, "/asm.Customer/GetAllCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) AddTagsCustomer(ctx context.Context, in *AddTagsCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error) {
	out := new(CustomerModel)
	err := c.cc.Invoke(ctx, "/asm.Customer/AddTagsCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerClient) DeleteTagsOfCustomer(ctx context.Context, in *DeleteTagsOfCustomerRequest, opts ...grpc.CallOption) (*CustomerModel, error) {
	out := new(CustomerModel)
	err := c.cc.Invoke(ctx, "/asm.Customer/DeleteTagsOfCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServer is the server API for Customer service.
// All implementations must embed UnimplementedCustomerServer
// for forward compatibility
type CustomerServer interface {
	CreateCustomer(context.Context, *CustomerModel) (*CustomerModel, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*CustomerModel, error)
	UpdateCustomer(context.Context, *CustomerModel) (*CustomerModel, error)
	DeleteCustomer(context.Context, *CustomerModel) (*DeleteCustomerResponse, error)
	GetAllCustomer(context.Context, *GetAllCustomerRequest) (*AllCustomerResponse, error)
	AddTagsCustomer(context.Context, *AddTagsCustomerRequest) (*CustomerModel, error)
	DeleteTagsOfCustomer(context.Context, *DeleteTagsOfCustomerRequest) (*CustomerModel, error)
	mustEmbedUnimplementedCustomerServer()
}

// UnimplementedCustomerServer must be embedded to have forward compatible implementations.
type UnimplementedCustomerServer struct {
}

func (UnimplementedCustomerServer) CreateCustomer(context.Context, *CustomerModel) (*CustomerModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCustomer not implemented")
}
func (UnimplementedCustomerServer) GetCustomer(context.Context, *GetCustomerRequest) (*CustomerModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCustomer not implemented")
}
func (UnimplementedCustomerServer) UpdateCustomer(context.Context, *CustomerModel) (*CustomerModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCustomer not implemented")
}
func (UnimplementedCustomerServer) DeleteCustomer(context.Context, *CustomerModel) (*DeleteCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCustomer not implemented")
}
func (UnimplementedCustomerServer) GetAllCustomer(context.Context, *GetAllCustomerRequest) (*AllCustomerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCustomer not implemented")
}
func (UnimplementedCustomerServer) AddTagsCustomer(context.Context, *AddTagsCustomerRequest) (*CustomerModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTagsCustomer not implemented")
}
func (UnimplementedCustomerServer) DeleteTagsOfCustomer(context.Context, *DeleteTagsOfCustomerRequest) (*CustomerModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTagsOfCustomer not implemented")
}
func (UnimplementedCustomerServer) mustEmbedUnimplementedCustomerServer() {}

// UnsafeCustomerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomerServer will
// result in compilation errors.
type UnsafeCustomerServer interface {
	mustEmbedUnimplementedCustomerServer()
}

func RegisterCustomerServer(s grpc.ServiceRegistrar, srv CustomerServer) {
	s.RegisterService(&Customer_ServiceDesc, srv)
}

func _Customer_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).CreateCustomer(ctx, req.(*CustomerModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_UpdateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).UpdateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/UpdateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).UpdateCustomer(ctx, req.(*CustomerModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeleteCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomerModel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeleteCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/DeleteCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeleteCustomer(ctx, req.(*CustomerModel))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_GetAllCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).GetAllCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/GetAllCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).GetAllCustomer(ctx, req.(*GetAllCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_AddTagsCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTagsCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).AddTagsCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/AddTagsCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).AddTagsCustomer(ctx, req.(*AddTagsCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Customer_DeleteTagsOfCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagsOfCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServer).DeleteTagsOfCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/asm.Customer/DeleteTagsOfCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServer).DeleteTagsOfCustomer(ctx, req.(*DeleteTagsOfCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Customer_ServiceDesc is the grpc.ServiceDesc for Customer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Customer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asm.Customer",
	HandlerType: (*CustomerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _Customer_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _Customer_GetCustomer_Handler,
		},
		{
			MethodName: "UpdateCustomer",
			Handler:    _Customer_UpdateCustomer_Handler,
		},
		{
			MethodName: "DeleteCustomer",
			Handler:    _Customer_DeleteCustomer_Handler,
		},
		{
			MethodName: "GetAllCustomer",
			Handler:    _Customer_GetAllCustomer_Handler,
		},
		{
			MethodName: "AddTagsCustomer",
			Handler:    _Customer_AddTagsCustomer_Handler,
		},
		{
			MethodName: "DeleteTagsOfCustomer",
			Handler:    _Customer_DeleteTagsOfCustomer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/customer.proto",
}
